//
// Created by dzordzu on 02.01.19.
//

#ifndef GENETIC_ALGORITHM_GENETICALGORITHM_H
#define GENETIC_ALGORITHM_GENETICALGORITHM_H

#include "Genotype.h"

#endif //GENETIC_ALGORITHM_GENETICALGORITHM_H
